package cli

import (
	"encoding/json"
	"fmt"
	"math/rand"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/devcontainers/cli/internal/jsonc"
	"github.com/devcontainers/cli/internal/log"
	"github.com/devcontainers/cli/internal/pfs"
)

// testLibraryScript is the bash test helper library that provides check() and reportResults().
// Matches TS testLibraryScript from featuresCLI/utils.ts.
const testLibraryScript = `#!/bin/bash
SCRIPT_FOLDER="$(cd "$(dirname $0)" && pwd)"
USERNAME=${1:-root}

if [ -z $HOME ]; then
    HOME="/root"
fi

FAILED=()

echoStderr()
{
    echo "$@" 1>&2
}

check() {
    LABEL=$1
    shift
    echo -e "\n"
    echo -e "Testing '$LABEL'"
    if "$@"; then
        echo -e "\n"
        echo "Passed '$LABEL'!"
        return 0
    else
        echo -e "\n"
        echoStderr "$LABEL check failed."
        FAILED+=("$LABEL")
        return 1
    fi
}

reportResults() {
    if [ ${#FAILED[@]} -ne 0 ]; then
        echo -e "\n"
        echoStderr -e "Failed tests: ${FAILED[@]}"
        exit 1
    else
        echo -e "\n"
        echo -e "Test Passed!"
        exit 0
    fi
}
`

type testResult struct {
	Name   string
	Status testStatus
	Detail string
}

type testStatus string

const (
	testPassed  testStatus = "passed"
	testFailed  testStatus = "failed"
	testSkipped testStatus = "skipped"
	testError   testStatus = "error"
)

// runFeaturesTestCommand implements the features test runner.
// It creates temporary projects, spins up containers, and runs test scripts.
func runFeaturesTestCommand(
	logger log.Log,
	collectionFolder string,
	featuresList []string,
	filter string,
	globalOnly bool,
	skipScenarios bool,
	skipAuto bool,
	skipDuplicate bool,
	baseImage string,
	remoteUser string,
	preserveContainers bool,
	quiet bool,
	permitRandomization bool,
) int {
	srcDir := filepath.Join(collectionFolder, "src")
	testDir := filepath.Join(collectionFolder, "test")

	if !pfs.IsDir(srcDir) || !pfs.IsDir(testDir) {
		logger.Write(fmt.Sprintf("Folder %q does not contain required 'src' and 'test' folders.", collectionFolder), log.LevelError)
		return 1
	}

	fmt.Println("┌ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ┐")
	fmt.Println("|    Dev Container Features      |")
	fmt.Println("└ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ┘")
	fmt.Println()

	var results []testResult

	if globalOnly {
		results = runGlobalTests(logger, collectionFolder, filter, baseImage, remoteUser, quiet)
	} else {
		// Discover features to test
		features := featuresList
		if len(features) == 0 {
			entries, err := os.ReadDir(testDir)
			if err != nil {
				logger.Write(fmt.Sprintf("Failed to discover feature tests: %v", err), log.LevelError)
				return 1
			}
			for _, e := range entries {
				if e.IsDir() && e.Name() != "_global" {
					features = append(features, e.Name())
				}
			}
		}

		if len(features) == 0 {
			logger.Write("No features to test.", log.LevelError)
			return 1
		}

		if permitRandomization {
			rand.Shuffle(len(features), func(i, j int) { features[i], features[j] = features[j], features[i] })
		}

		logger.Write(fmt.Sprintf("Features: %s", strings.Join(features, ", ")), log.LevelInfo)
		logger.Write(fmt.Sprintf("Base image: %s", baseImage), log.LevelInfo)

		// Run autogenerated tests (test.sh for each feature)
		if !skipAuto {
			results = append(results, runAutoTests(logger, collectionFolder, features, baseImage, remoteUser, quiet)...)
		}

		// Run scenario tests
		if !skipScenarios {
			for _, feature := range features {
				featureTestDir := filepath.Join(testDir, feature)
				results = append(results, runScenarioTests(logger, collectionFolder, featureTestDir, feature, filter, baseImage, remoteUser, quiet)...)
			}
		}

		// Run global tests (unless features were explicitly specified)
		if featuresList == nil {
			results = append(results, runGlobalTests(logger, collectionFolder, filter, baseImage, remoteUser, quiet)...)
		}
	}

	// Cleanup
	if !preserveContainers {
		cleanupTestContainers(logger)
	}

	return reportTestResults(results)
}

func runAutoTests(logger log.Log, collectionFolder string, features []string, baseImage, remoteUser string, quiet bool) []testResult {
	var results []testResult

	// Create a single container with all features installed
	tmpDir, err := os.MkdirTemp("", "devcontainer-test-")
	if err != nil {
		logger.Write(fmt.Sprintf("Failed to create temp dir: %v", err), log.LevelError)
		return []testResult{{Name: "autogenerated setup", Status: testError, Detail: err.Error()}}
	}
	defer os.RemoveAll(tmpDir)

	// Generate devcontainer.json with local feature paths
	dcDir := filepath.Join(tmpDir, ".devcontainer")
	if err := pfs.MkdirAll(dcDir); err != nil {
		return []testResult{{Name: "autogenerated setup", Status: testError, Detail: err.Error()}}
	}

	featureEntries := make([]string, 0, len(features))
	for _, f := range features {
		// Copy feature source to temp dir
		srcPath := filepath.Join(collectionFolder, "src", f)
		destPath := filepath.Join(dcDir, f)
		if err := copyDir(srcPath, destPath); err != nil {
			logger.Write(fmt.Sprintf("Failed to stage feature %s: %v", f, err), log.LevelError)
			return []testResult{{Name: f, Status: testError, Detail: "could not stage feature: " + err.Error()}}
		}
		featureEntries = append(featureEntries, fmt.Sprintf(`"./%s": {}`, f))
	}

	remoteUserLine := ""
	if remoteUser != "" {
		remoteUserLine = fmt.Sprintf(`"remoteUser": "%s",`, remoteUser)
	}

	configJSON := fmt.Sprintf(`{
	%s
	"image": "%s",
	"features": {
		%s
	}
}`, remoteUserLine, baseImage, strings.Join(featureEntries, ",\n\t\t"))

	if err := os.WriteFile(filepath.Join(dcDir, "devcontainer.json"), []byte(configJSON), 0644); err != nil {
		return []testResult{{Name: "autogenerated setup", Status: testError, Detail: err.Error()}}
	}

	// Build and start container
	logger.Write("Building test container...", log.LevelInfo)
	containerId, err := upTestContainer(tmpDir, quiet)
	if err != nil {
		logger.Write(fmt.Sprintf("Failed to start container: %v", err), log.LevelError)
		return []testResult{{Name: "autogenerated setup", Status: testError, Detail: err.Error()}}
	}

	// Run test.sh for each feature
	for _, feature := range features {
		testScript := filepath.Join(collectionFolder, "test", feature, "test.sh")
		if !pfs.IsFile(testScript) {
			logger.Write(fmt.Sprintf("No test.sh found for %s, skipping", feature), log.LevelWarning)
			results = append(results, testResult{Name: feature, Status: testSkipped, Detail: "test.sh not found"})
			continue
		}

		// Copy test files and library into workspace
		if err := copyDir(filepath.Join(collectionFolder, "test", feature), filepath.Join(tmpDir, feature)); err != nil {
			results = append(results, testResult{Name: feature, Status: testError, Detail: err.Error()})
			continue
		}
		if err := os.WriteFile(filepath.Join(tmpDir, "dev-container-features-test-lib"), []byte(testLibraryScript), 0755); err != nil {
			results = append(results, testResult{Name: feature, Status: testError, Detail: err.Error()})
			continue
		}

		logger.Write(fmt.Sprintf("Running test for %s...", feature), log.LevelInfo)
		passed := execTestInContainer(containerId, feature+"/test.sh", tmpDir)
		status := testFailed
		if passed {
			status = testPassed
		}
		results = append(results, testResult{Name: feature, Status: status})
	}

	return results
}

func runScenarioTests(logger log.Log, collectionFolder, featureTestDir, feature, filter, baseImage, remoteUser string, quiet bool) []testResult {
	var results []testResult

	scenariosPath := filepath.Join(featureTestDir, "scenarios.json")
	if !pfs.IsFile(scenariosPath) {
		return results
	}

	data, err := os.ReadFile(scenariosPath)
	if err != nil {
		return []testResult{{Name: feature + " scenarios", Status: testError, Detail: err.Error()}}
	}

	var scenarios map[string]json.RawMessage
	if err := jsonc.Unmarshal(data, &scenarios); err != nil {
		logger.Write(fmt.Sprintf("Failed to parse scenarios.json: %v", err), log.LevelError)
		return []testResult{{Name: feature + " scenarios", Status: testError, Detail: err.Error()}}
	}

	for scenarioName, scenarioConfig := range scenarios {
		if filter != "" && !strings.Contains(scenarioName, filter) {
			continue
		}

		scriptPath := filepath.Join(featureTestDir, scenarioName+".sh")
		if !pfs.IsFile(scriptPath) {
			logger.Write(fmt.Sprintf("Missing script %s.sh for scenario, skipping", scenarioName), log.LevelWarning)
			results = append(results, testResult{Name: scenarioName, Status: testSkipped, Detail: "scenario script not found"})
			continue
		}

		logger.Write(fmt.Sprintf("Running scenario: %s", scenarioName), log.LevelInfo)

		// Create temp project for this scenario
		tmpDir, err := os.MkdirTemp("", "devcontainer-scenario-")
		if err != nil {
			results = append(results, testResult{Name: scenarioName, Status: testError, Detail: err.Error()})
			continue
		}
		dcDir := filepath.Join(tmpDir, ".devcontainer")
		if err := pfs.MkdirAll(dcDir); err != nil {
			results = append(results, testResult{Name: scenarioName, Status: testError, Detail: err.Error()})
			os.RemoveAll(tmpDir)
			continue
		}

		// Parse scenario config and update feature paths
		var config map[string]interface{}
		if err := json.Unmarshal(scenarioConfig, &config); err != nil {
			results = append(results, testResult{Name: scenarioName, Status: testError, Detail: err.Error()})
			os.RemoveAll(tmpDir)
			continue
		}

		// Copy feature sources for any local features
		if feats, ok := config["features"].(map[string]interface{}); ok {
			updated := make(map[string]interface{})
			for fid, fval := range feats {
				if !strings.Contains(fid, "/") {
					// Local feature reference
					srcPath := filepath.Join(collectionFolder, "src", fid)
					if pfs.IsDir(srcPath) {
						if err := copyDir(srcPath, filepath.Join(dcDir, fid)); err != nil {
							results = append(results, testResult{Name: scenarioName, Status: testError, Detail: err.Error()})
							os.RemoveAll(tmpDir)
							return results
						}
					}
					updated["./"+fid] = fval
				} else {
					updated[fid] = fval
				}
			}
			config["features"] = updated
		}

		configData, err := json.MarshalIndent(config, "", "  ")
		if err != nil {
			results = append(results, testResult{Name: scenarioName, Status: testError, Detail: err.Error()})
			os.RemoveAll(tmpDir)
			continue
		}
		if err := os.WriteFile(filepath.Join(dcDir, "devcontainer.json"), configData, 0644); err != nil {
			results = append(results, testResult{Name: scenarioName, Status: testError, Detail: err.Error()})
			os.RemoveAll(tmpDir)
			continue
		}

		containerId, err := upTestContainer(tmpDir, quiet)
		if err != nil {
			logger.Write(fmt.Sprintf("Failed to start scenario container: %v", err), log.LevelError)
			results = append(results, testResult{Name: scenarioName, Status: testError, Detail: err.Error()})
			os.RemoveAll(tmpDir)
			continue
		}

		// Copy test files
		if err := copyDir(featureTestDir, filepath.Join(tmpDir, filepath.Base(featureTestDir))); err != nil {
			results = append(results, testResult{Name: scenarioName, Status: testError, Detail: err.Error()})
			os.RemoveAll(tmpDir)
			continue
		}
		if err := os.WriteFile(filepath.Join(tmpDir, "dev-container-features-test-lib"), []byte(testLibraryScript), 0755); err != nil {
			results = append(results, testResult{Name: scenarioName, Status: testError, Detail: err.Error()})
			os.RemoveAll(tmpDir)
			continue
		}

		passed := execTestInContainer(containerId, filepath.Base(featureTestDir)+"/"+scenarioName+".sh", tmpDir)
		status := testFailed
		if passed {
			status = testPassed
		}
		results = append(results, testResult{Name: scenarioName, Status: status})

		os.RemoveAll(tmpDir)
	}

	return results
}

func runGlobalTests(logger log.Log, collectionFolder, filter, baseImage, remoteUser string, quiet bool) []testResult {
	globalDir := filepath.Join(collectionFolder, "test", "_global")
	if !pfs.IsDir(globalDir) {
		return nil
	}
	return runScenarioTests(logger, collectionFolder, globalDir, "_global", filter, baseImage, remoteUser, quiet)
}

func upTestContainer(workspaceFolder string, quiet bool) (string, error) {
	// Tag the container so cleanupTestContainers (which filters on this label)
	// can remove it — otherwise every test run leaks a container.
	args := []string{"up", "--workspace-folder", workspaceFolder, "--skip-post-create", "--log-level", "info", "--id-label", "devcontainer.is_test_run=true"}
	if quiet {
		args = append(args, "--log-level", "error")
	}

	// Use ourselves to run the container
	self, _ := os.Executable()
	cmd := exec.Command(self, args...)
	cmd.Stderr = os.Stderr

	out, err := cmd.Output()
	if err != nil {
		return "", fmt.Errorf("devcontainer up failed: %w", err)
	}

	var result map[string]interface{}
	if err := json.Unmarshal(out, &result); err != nil {
		return "", fmt.Errorf("parse up output: %w", err)
	}

	if result["outcome"] != "success" {
		return "", fmt.Errorf("up failed: %v", result["description"])
	}

	containerId, _ := result["containerId"].(string)
	return containerId, nil
}

func execTestInContainer(containerId, testScript, workspaceFolder string) bool {
	self, _ := os.Executable()
	// The workspace is mounted at /workspaces/<name>; the test lib and scripts live
	// there, so cd into it (not its parent) before sourcing them.
	containerWs := "/workspaces/" + filepath.Base(workspaceFolder)
	cmd := exec.Command(self, "exec", "--container-id", containerId, "--", "bash", "-c",
		fmt.Sprintf("cd %s && source dev-container-features-test-lib && source %s && reportResults", containerWs, testScript))
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run() == nil
}

func cleanupTestContainers(logger log.Log) {
	cmd := exec.Command("docker", "ps", "-a", "--filter", "label=devcontainer.is_test_run=true", "--format", "{{.ID}}")
	out, _ := cmd.Output()
	ids := strings.Fields(strings.TrimSpace(string(out)))
	if len(ids) > 0 {
		logger.Write(fmt.Sprintf("Cleaning up %d test containers...", len(ids)), log.LevelInfo)
		for _, id := range ids {
			exec.Command("docker", "rm", "-f", id).Run()
		}
	}
}

func reportTestResults(results []testResult) int {
	fmt.Println()
	// Format matches the TS test report: `${prefix} ${msg}` with a leading-space
	// prefix on the header and ✅/❌ prefixes on the result lines.
	fmt.Println("  ================== TEST REPORT ==================")
	allPassed := true
	for _, r := range results {
		switch r.Status {
		case testPassed:
			fmt.Printf("✅ Passed:      '%s'\n", r.Name)
		case testSkipped:
			fmt.Printf("⚪ Skipped:     '%s' (%s)\n", r.Name, r.Detail)
		case testError:
			fmt.Printf("❌ Error:       '%s' (%s)\n", r.Name, r.Detail)
			allPassed = false
		default:
			fmt.Printf("❌ Failed:      '%s'\n", r.Name)
			allPassed = false
		}
	}
	fmt.Println()
	if allPassed {
		return 0
	}
	return 1
}

func copyDir(src, dst string) error {
	return filepath.Walk(src, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		rel, _ := filepath.Rel(src, path)
		target := filepath.Join(dst, rel)
		if info.IsDir() {
			return os.MkdirAll(target, 0755)
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		return os.WriteFile(target, data, info.Mode())
	})
}
